version: "3.8"

services:
  nextjs:
    build:
      context: "."
      dockerfile: ./compose/development/Dockerfile
    image: fp_nextjs_dev
    container_name: fp_nextjs_dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3000:3000'
    stdin_open: true
